---
  - name: "Install php"
    package:
      name: php7.0
      state: present

  - name: "Install php-fpm"
    package:
      name: php-fpm
      state: present

  - name: "Overwrite nginx.conf"
    copy:
      src: files/etc/nginx/sites-available/default
      dest: /etc/nginx/sites-available/default
    notify: Restart nginx
