---
  - name: "Install git-core"
    package:
      name: git-core
      state: present

  - name: "Install nginx"
    package:
      name: nginx
      state: present

  - name: "Enable nginx"
    service:
      name: nginx
      state: started
