---
  - name: "Install serverspec"
    package:
      name: ruby-serverspec
      state: present

  - name: "Check for /tmp/ansible"
    stat: path=/tmp/ansible
    register: tmp_ansible

  - name: "Check for /vagrant"
    stat: path=/vagrant
    register: tmp_vagrant

  - name: "Run serverspec on ec2"
    shell: rake spec:localhost
    args:
      chdir: /tmp/ansible/ansible
    when: tmp_ansible.stat.exists
    register: serverspec

  - name: "Run serverspec in vagrant"
    shell: rake spec:localhost
    args:
      chdir: /vagrant/ansible
    when: tmp_vagrant.stat.exists
    register: serverspec

  - name: "Display results from serverspec"
    debug: "msg=`{{ serverspec.stdout }}`"
